apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-to-do-deployment
  labels:
    app: frontend-to-do
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-to-do
  template:
    metadata:
      labels:
        app: frontend-to-do
    spec:
      containers:
        - name: frontend-to-do
          image: kraskobohdan/to-do-app:backend
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-to-do
spec:
  selector:
    app: frontend-to-do
  type: LoadBalancer
  externalIPs:
  - 10.1.243.192
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
